version: 2
updates:
- package-ecosystem: docker
  directory: "/mpcontribs-kernel-gateway"
  schedule:
    interval: weekly
    time: '08:00'
    timezone: US/Pacific
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/mpcontribs-portal"
  schedule:
    interval: weekly
    time: '08:00'
    timezone: US/Pacific
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/mpcontribs-portal"
  schedule:
    interval: weekly
    time: '08:00'
    timezone: US/Pacific
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/mpcontribs-api"
  schedule:
    interval: weekly
    time: '08:00'
    timezone: US/Pacific
  open-pull-requests-limit: 10
