language: python
install: 
  - pip install numpy==1.9.2
  - pip install scipy==0.16.0
  - pip install -r requirements.txt
script: nosetests --nocapture --with-coverage
sudo: false
after_success:
  - coveralls
