# https://gist.github.com/dan-blanchard/7045057
# https://github.com/mroberge/hydrofunctions/blob/master/.travis.yml
language: python
python:
  - "2.7"
git:
  submodules: false
before_install:
  - sudo apt-get install -y apache2-dev
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  - git submodule update --init --recursive
install:
  - pip install --upgrade pip setuptools wheel
  - pip install pytest pytest-cov coveralls
  - pip install --only-binary=numpy,scipy,pandas,Ipython,matplotlib numpy scipy pandas ipython matplotlib
  - pip install -e . --process-dependency-links
  - pip install -U coverage
  - pip install codacy-coverage
script:
  - py.test --doctest-modules --cov mpcontribs/io/core --no-cov-on-fail --cov-report term-missing:skip-covered mpcontribs/io/core
after_success:
  - coverage xml
  - coveralls --config_file .coveragerc
  - python-codacy-coverage -r coverage.xml
notifications:
  email:
    on_success: change
    on_failure: always
notifications:
  slack: mpcontribs:8BEeanYMtnJ2hnRyCM6eOYPD
