version: '3'

services:
  web:
    build: .
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    volumes:
      - ./test_site:/app/test_site
      - ./mpcontribs-portal:/app/mpcontribs-portal
      - ./mpcontribs-explorer:/app/mpcontribs-explorer
      - ./mpcontribs-users:/app/mpcontribs-users
      - ./mpcontribs-webtzite:/app/mpcontribs-webtzite
      - ./mpcontribs-io:/app/mpcontribs-io
      - ./mpcontribs-client:/app/mpcontribs-client
    ports:
      - "8080:8080"
  api:
    build: ./mpcontribs-api
    volumes:
      - ./mpcontribs-api:/app
    environment:
      - FLASK_ENV=development
      - MPCONTRIBS_MONGO_HOST=$MPCONTRIBS_MONGO_HOST
      - GATEWAY_HOST=kernel_gateway:8888
    ports:
      - "5000:5000"
  chrome:
    build:
        context: .
        dockerfile: DockerfileChrome
    environment:
        - START_XVFB=false
    ports:
      - "4444:4444"
  kernel_gateway:
    build:
      context: .
      dockerfile: DockerfileKernelGateway
    volumes:
      - ./mpcontribs-io:/src/mpcontribs-io
      - ./mpcontribs-client:/src/mpcontribs-client
    ports:
      - "8888:8888"
    environment:
      - KG_ALLOW_ORIGIN='*'
  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
