version: '2.2'

services:

    portal-ml:
        build: ./mpcontribs-portal
        env_file:
            - ./deployments/ml.materialsproject.org.env
        depends_on:
            - api-ml
        volumes: *portal-volumes
        ports:
            - "8082:8082"

    portal-ls:
        build: ./mpcontribs-portal
        env_file:
            - ./deployments/lightsources.materialsproject.org.env
        depends_on:
            - api-ls
        volumes: *portal-volumes
        ports:
            - "8083:8083"


    api-ml:
        build:
            context: ./mpcontribs-api
        depends_on:
            - redis
            - orca
            - kernel_gateway
            - supercronic
            #- datadog
        volumes:
            - ./mpcontribs-api:/app
        env_file:
            - ./deployments/ml.materialsproject.org.env
        environment: *dev-env
        ports:
            - "5002:5002"

    api-ls:
        build:
            context: ./mpcontribs-api
        depends_on:
            - redis
            - orca
            - kernel_gateway
            - supercronic
            #- datadog
        volumes:
            - ./mpcontribs-api:/app
        env_file:
            - ./deployments/lightsources.materialsproject.org.env
        environment: *dev-env
        ports:
            - "5003:5003"

  contribs-docs:
    image: squidfunk/mkdocs-material:4.6.3
    command: serve --dev-addr=0.0.0.0:8081
    volumes:
        - .:/docs
    ports:
        - "8081:8081"


  datadog:
    build: ./MPContribs/mpcontribs-sidecars/datadog-agent
    depends_on:
      - redis
    environment:
      - DD_API_KEY=$DD_API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - "8125:8125/udp"
