version: '2.2'

services:

    portal:
        cpus: 1
        mem_limit: 1G
        mem_reservation: 250m
        build: ./mpcontribs-portal
        env_file:
            - ./deployments/$DEPLOYMENT.env
        depends_on:
            - api
        volumes:
            - ./mpcontribs-portal/mpcontribs:/app/mpcontribs
            - /app/mpcontribs/portal/templates/notebooks/
            - ./mpcontribs-portal/webpack.config.js:/app/webpack.config.js
            - ./mpcontribs-portal/package.json:/app/package.json
            - ./mpcontribs-portal/wsgi.py:/app/wsgi.py
            - ./mpcontribs-portal/settings.py:/app/settings.py
        ports:
            - "8080:8080"
            - "8082:8082"
            - "8083:8083"

    api:
        cpus: 1
        mem_limit: 1G
        mem_reservation: 600m
        build:
            context: ./mpcontribs-api
        depends_on:
            - redis
            - chrome
            - kernel_gateway
            - xray
        volumes:
            - ./mpcontribs-api:/app
        env_file:
            - ./deployments/$DEPLOYMENT.env
        environment:
            FLASK_ENV: development
            MPCONTRIBS_MONGO_HOST: $MPCONTRIBS_MONGO_HOST
            GATEWAY_HOST: kernel_gateway:8888
            AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
            AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
            AWS_SNS_TOPIC_ARN: $AWS_SNS_TOPIC_ARN
            AWS_DEFAULT_REGION: us-east-1
        ports:
            - "5000:5000"
            - "5002:5002"

    redis:
        image: redis:alpine
        environment:
            - ALLOW_EMPTY_PASSWORD=yes

    chrome:
        build: mpcontribs-sidecars/chrome
        mem_limit: 1G
        mem_reservation: 100m
        cpus: 1
        environment:
            - START_XVFB=false
        ports:
            - "4444:4444"

    kernel_gateway:
        mem_limit: 1G
        mem_reservation: 100m
        cpus: 1
        env_file:
            - ./deployments/$DEPLOYMENT.env
        environment:
            KG_ALLOW_ORIGIN: '*'
            GATEWAY_HOST: kernel_gateway:8888
        build: ./mpcontribs-sidecars/kernel_gateway

    xray:
        mem_limit: 1G
        mem_reservation: 100m
        cpus: 1
        env_file:
            - ./deployments/$DEPLOYMENT.env
        # run in local mode to prevent it from trying to read EC2 instance metadata
        command: -o
        volumes:
            - ~/.aws/:/root/.aws/:ro
        build: ./mpcontribs-sidecars/xray-daemon
        # port mapping only needed to use daemon from local machine
        ports:
            - "2000:2000/udp"

    # OTHER
    docs:
        image: squidfunk/mkdocs-material
        command: serve --dev-addr=0.0.0.0:8081
        volumes:
            - .:/docs
        ports:
            - "8081:8081"

    jhub:
        mem_limit: 1G
        mem_reservation: 250m
        cpus: 1
        build:
            context: .
            dockerfile: binder/DockerfileJhub
        environment:
            - NODE_ENV=development
            - MAPI_KEY=$MAPI_KEY
            - DOCKER_NETWORK_NAME=mpcontribs_default
            - DOCKER_NOTEBOOK_DIR=/home/jovyan
        depends_on:
            - api
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        ports:
            - "8000:8000"

volumes:
  data-volume:
      driver_opts:
          type: none
          device: $PWD
          o: bind
