version: '2.2'

services:

    web:
        mem_limit: 1G
        mem_reservation: 250m
        cpus: 1
        build: .
        environment:
            - NODE_ENV=development
        depends_on:
            - api
            - jhub
            - docs
        volumes:
            - ./test_site:/app/test_site
            - ./webpack.config.js:/app/webpack.config.js
            - ./package.json:/app/package.json
            - ./mpcontribs-portal:/app/mpcontribs-portal
            - ./mpcontribs-users:/app/mpcontribs-users
            - ./mpcontribs-webtzite:/app/mpcontribs-webtzite
            - ./mpcontribs-io:/app/mpcontribs-io
            - ./mpcontribs-client:/app/mpcontribs-client
            - ./run_server.py:/app/run_server.py
        ports:
            - "8080:8080"
            - "9000:9000"

    api:
        mem_limit: 1G
        mem_reservation: 250m
        cpus: 1
        build: ./mpcontribs-api
        depends_on:
            - chrome
            - kernel_gateway
        volumes:
            - ./mpcontribs-api:/app
        environment:
            - FLASK_ENV=development
            - MPCONTRIBS_MONGO_HOST=$MPCONTRIBS_MONGO_HOST
            - GATEWAY_HOST=kernel_gateway:8888
            - MPCONTRIBS_MAILGUN_USERNAME=$MPCONTRIBS_MAILGUN_USERNAME
            - MPCONTRIBS_MAILGUN_PASSWORD=$MPCONTRIBS_MAILGUN_PASSWORD
        ports:
            - "5000:5000"

    chrome:
        mem_limit: 1G
        mem_reservation: 100m
        cpus: 1
        environment:
            - START_XVFB=false
        ports:
            - "4444:4444"
        build:
            context: .
            dockerfile: DockerfileChrome

    kernel_gateway:
        mem_limit: 1G
        mem_reservation: 100m
        cpus: 1
        volumes:
            - ./mpcontribs-io:/src/mpcontribs-io
            - ./mpcontribs-client:/src/mpcontribs-client
        environment:
            - KG_ALLOW_ORIGIN='*'
        build:
            context: .
            dockerfile: DockerfileKernelGateway

    test:
        build:
            context: ./mpcontribs-api
            dockerfile: DockerfileTest

    docs:
        image: squidfunk/mkdocs-material
        volumes:
            - .:/docs
        ports:
            - "8081:8000"

    jhub:
        build:
            context: .
            dockerfile: DockerfileJhub
        environment:
            - NODE_ENV=development
            - MAPI_KEY=$MAPI_KEY
            - TASK_CLUSTER_NAME=$TASK_CLUSTER_NAME
            - TASK_DEFINITION_ARN=$TASK_DEFINITION_ARN
            - TASK_ROLE_ARN=$TASK_ROLE_ARN
            - TASK_SECURITY_GROUPS=$TASK_SECURITY_GROUPS
            - TASK_SUBNETS=$TASK_SUBNETS
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - DOCKER_NETWORK_NAME=mpcontribs_default
            - DOCKER_NOTEBOOK_DIR=/home/jovyan
        depends_on:
            - api
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
        ports:
            - "8000:8000"

volumes:
  data-volume:
      driver_opts:
          type: none
          device: $PWD
          o: bind
