version: '2.2'

services:

    web:
        mem_limit: 1G
        mem_reservation: 250m
        cpus: 1
        build: .
        environment:
            - NODE_ENV=development
        depends_on:
            - api
        volumes:
            - ./test_site:/app/test_site
            - ./webpack.config.js:/app/webpack.config.js
            - ./package.json:/app/package.json
            - ./mpcontribs-portal:/app/mpcontribs-portal
            - ./mpcontribs-users:/app/mpcontribs-users
            - ./mpcontribs-webtzite:/app/mpcontribs-webtzite
            - ./mpcontribs-io:/app/mpcontribs-io
            - ./mpcontribs-client:/app/mpcontribs-client
        ports:
            - "8080:8080"

    api:
        mem_limit: 1G
        mem_reservation: 250m
        cpus: 1
        build: ./mpcontribs-api
        depends_on:
            - chrome
            - kernel_gateway
        volumes:
            - ./mpcontribs-api:/app
        environment:
            - FLASK_ENV=development
            - MPCONTRIBS_MONGO_HOST=$MPCONTRIBS_MONGO_HOST
            - GATEWAY_HOST=kernel_gateway:8888
            - MPCONTRIBS_MAILGUN_USERNAME=$MPCONTRIBS_MAILGUN_USERNAME
            - MPCONTRIBS_MAILGUN_PASSWORD=$MPCONTRIBS_MAILGUN_PASSWORD
        ports:
            - "5000:5000"

    chrome:
        mem_limit: 1G
        mem_reservation: 100m
        cpus: 1
        environment:
            - START_XVFB=false
        ports:
            - "4444:4444"
        build:
            context: .
            dockerfile: DockerfileChrome

    kernel_gateway:
        mem_limit: 1G
        mem_reservation: 100m
        cpus: 1
        volumes:
            - ./mpcontribs-io:/src/mpcontribs-io
            - ./mpcontribs-client:/src/mpcontribs-client
        environment:
            - KG_ALLOW_ORIGIN='*'
        build:
            context: .
            dockerfile: DockerfileKernelGateway

    test:
        build:
            context: ./mpcontribs-api
            dockerfile: DockerfileTest

    docs:
        image: squidfunk/mkdocs-material
        volumes:
            - .:/docs
        ports:
            - "8000:8081"

    # build image first:
    # $ jupyter-repo2docker --user-name jovyan --user-id 1000 --image-name mpcontribs_r2d --no-run .
    r2d:
        image: mpcontribs_r2d
        ports:
            - "8888:8888"
        environment:
            - NODE_ENV=development
        volumes:
            - ./mpcontribs-io:/home/jovyan/mpcontribs-io
            - ./mpcontribs-client:/home/jovyan/mpcontribs-client
            - ./binder/notebooks:/home/jovyan/binder/notebooks
            - ./webpack-binder.config.js:/home/jovyan/webpack.config.js
            - ./binder/binder.js:/home/jovyan/binder.js
            - ./mpcontribs-webtzite:/home/jovyan/mpcontribs-webtzite

    jhub:
        build: ./jhub
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - "8000:8000"
