# docker pull squidfunk/mkdocs-material
# docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
# docker run --rm -it -v ~/.ssh/tschaume@mac14:/root/.ssh/id_rsa -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy
site_name: MPContribs
theme:
    name: 'material'
markdown_extensions:
    - codehilite
nav:
    - Home: index.md
    - API: api.md
