AWSTemplateFormatVersion: '2010-09-09'
Description: MPContribs Services
Parameters:
  PipelineName:
    Type: String
  EnvironmentName:
    Type: String
    Description: A name for the environment that this cloudformation will be part of.
                 Used to locate other resources in the same environment.
  Repository:
    Type: String
    Description: ECR repository name
  MongoHost:
    Type: String
    Description: MongoDB host that the app connects to.
  AwsAccessKeyId:
    Type: String
  AwsSecretAccessKey:
    Type: String
  SnsAdminTopicArn:
    Type: String
  ServiceName:
    Type: String
    Default: MPContribs
    Description: A name for the service
  Tag:
    Type: String
    Description: short git tag used for image builds
  #DdApiKey:
  #  Type: String

Resources:
  # A log group for storing the container logs for this service
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]

  # A role for the service so it can access the tables
  AppServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: app-sqlite
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:ListBucket"
            Resource:
              - "arn:aws:s3:::mpcontribs-sqlite/db.sqlite3"
              - "arn:aws:s3:::mpcontribs-sqlite"

  # The task definition. This is a simple metadata description of what
  # container to run, and what resource requirements it has.
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref 'ServiceName'
      Cpu: 4096
      Memory: 12288
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn:
        Fn::ImportValue:
          !Join [':', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'ECSTaskExecutionRole']]
      TaskRoleArn: !Ref 'AppServiceRole'
      ContainerDefinitions:
        - Name: api
          MemoryReservation: 250
          Image: !Join ['', [
            !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
            !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
            !Ref 'Tag', '-api'
          ]]
          #DockerLabels:
          #  my.custom.label.service: !Join ['-', [
          #    !Ref 'PipelineName', !Ref 'EnvironmentName', !Ref 'ServiceName'
          #  ]]
          #  com.datadoghq.ad.instances: [{"host": "%%host%%", "port": "5000"}]
          #  com.datadoghq.ad.check_names: "[\"ecs_fargate\"]"
          #  com.datadoghq.ad.init_configs: "[{}]"
          DependsOn:
            - Condition: START
              ContainerName: orca
            - Condition: START
              ContainerName: gateway
            #- Condition: START
            #  ContainerName: datadog
          Environment:
            - Name: MAIL_DEFAULT_SENDER
              Value: "contribs@materialsproject.org"
            - Name: MPCONTRIBS_API_HOST
              Value: "localhost:5000"
            - Name: API_CNAME
              Value: "api.mpcontribs.org"
            - Name: API_PORT
              Value: "5000"
            - Name: PORTAL_CNAME
              Value: "portal.mpcontribs.org"
            - Name: PORTAL_PORT
              Value: "8080"
            - Name: MPCONTRIBS_DB_NAME
              Value: "mpcontribs-dev"
            - Name: MPCONTRIBS_MONGO_HOST
              Value: !Ref 'MongoHost'
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref 'AwsAccessKeyId'
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !Ref 'AwsSecretAccessKey'
            - Name: AWS_SNS_TOPIC_ARN
              Value: !Ref 'SnsAdminTopicArn'
            - Name: AWS_DEFAULT_REGION
              Value: !Ref 'AWS::Region'
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
            - Name: S3_DOWNLOADS_BUCKET
              Value: mpcontribs-downloads
            - Name: REDIS_ADDRESS
              Value:
                Fn::ImportValue:
                    !Join [':', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'ElastiCacheAddress']]
            - Name: DD_TRACE_AGENT_PORT
              Value: 8126
            - Name: DD_TRACE_AGENT_HOSTNAME
              Value: localhost
          PortMappings:
            - ContainerPort: 5000
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'ServiceName'
        - Name: api-ml
          MemoryReservation: 250
          Image: !Join ['', [
            !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
            !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
            !Ref 'Tag', '-api'
          ]]
          DependsOn:
            - Condition: START
              ContainerName: api
          Environment:
            - Name: MAIL_DEFAULT_SENDER
              Value: "contribs@materialsproject.org"
            - Name: MPCONTRIBS_API_HOST
              Value: "localhost:5002"
            - Name: API_CNAME
              Value: "ml-api.materialsproject.org"
            - Name: API_PORT
              Value: "5002"
            - Name: PORTAL_CNAME
              Value: "ml.materialsproject.org"
            - Name: PORTAL_PORT
              Value: "8082"
            - Name: MPCONTRIBS_DB_NAME
              Value: "mpcontribs-ml"
            - Name: TRADEMARK
              Value: "ML"
            - Name: NWORKERS
              Value: 1
            - Name: MPCONTRIBS_MONGO_HOST
              Value: !Ref 'MongoHost'
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref 'AwsAccessKeyId'
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !Ref 'AwsSecretAccessKey'
            - Name: AWS_SNS_TOPIC_ARN
              Value: !Ref 'SnsAdminTopicArn'
            - Name: AWS_DEFAULT_REGION
              Value: !Ref 'AWS::Region'
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
            - Name: S3_DOWNLOADS_BUCKET
              Value: mpcontribs-downloads
            - Name: REDIS_ADDRESS
              Value:
                Fn::ImportValue:
                    !Join [':', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'ElastiCacheAddress']]
          PortMappings:
            - ContainerPort: 5002
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'ServiceName'
        - Name: api-ls
          MemoryReservation: 250
          Image: !Join ['', [
            !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
            !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
            !Ref 'Tag', '-api'
          ]]
          DependsOn:
            - Condition: START
              ContainerName: api
          Environment:
            - Name: MAIL_DEFAULT_SENDER
              Value: "contribs@materialsproject.org"
            - Name: MPCONTRIBS_API_HOST
              Value: "localhost:5003"
            - Name: API_CNAME
              Value: "lightsources-api.materialsproject.org"
            - Name: API_PORT
              Value: "5003"
            - Name: PORTAL_CNAME
              Value: "lightsources.materialsproject.org"
            - Name: PORTAL_PORT
              Value: "8083"
            - Name: MPCONTRIBS_DB_NAME
              Value: "mpcontribs-ls"
            - Name: TRADEMARK
              Value: "LS"
            - Name: NWORKERS
              Value: 1
            - Name: MPCONTRIBS_MONGO_HOST
              Value: !Ref 'MongoHost'
            - Name: AWS_ACCESS_KEY_ID
              Value: !Ref 'AwsAccessKeyId'
            - Name: AWS_SECRET_ACCESS_KEY
              Value: !Ref 'AwsSecretAccessKey'
            - Name: AWS_SNS_TOPIC_ARN
              Value: !Ref 'SnsAdminTopicArn'
            - Name: AWS_DEFAULT_REGION
              Value: !Ref 'AWS::Region'
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
            - Name: S3_DOWNLOADS_BUCKET
              Value: mpcontribs-downloads
            - Name: REDIS_ADDRESS
              Value:
                Fn::ImportValue:
                    !Join [':', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'ElastiCacheAddress']]
          PortMappings:
            - ContainerPort: 5003
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'ServiceName'
        - Name: portal
          MemoryReservation: 70
          Image: !Join ['', [
            !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
            !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
            !Ref 'Tag', '-portal'
          ]]
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: MPCONTRIBS_API_HOST
              Value: "localhost:5000"
            - Name: API_CNAME
              Value: "api.mpcontribs.org"
            - Name: API_PORT
              Value: "5000"
            - Name: PORTAL_CNAME
              Value: "portal.mpcontribs.org"
            - Name: PORTAL_PORT
              Value: "8080"
            - Name: TRADEMARK
              Value: ""
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
          DependsOn:
            - Condition: START
              ContainerName: api
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'ServiceName'
        - Name: portal-ml
          MemoryReservation: 70
          Image: !Join ['', [
            !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
            !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
            !Ref 'Tag', '-portal'
          ]]
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: MPCONTRIBS_API_HOST
              Value: "localhost:5002"
            - Name: API_CNAME
              Value: "ml-api.materialsproject.org"
            - Name: API_PORT
              Value: "5002"
            - Name: PORTAL_CNAME
              Value: "ml.materialsproject.org"
            - Name: PORTAL_PORT
              Value: "8082"
            - Name: TRADEMARK
              Value: "ML"
            - Name: NWORKERS
              Value: 1
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
          DependsOn:
            - Condition: START
              ContainerName: api-ml
          PortMappings:
            - ContainerPort: 8082
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'ServiceName'
        - Name: portal-ls
          MemoryReservation: 70
          Image: !Join ['', [
            !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
            !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
            !Ref 'Tag', '-portal'
          ]]
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: MPCONTRIBS_API_HOST
              Value: "localhost:5003"
            - Name: API_CNAME
              Value: "lightsources-api.materialsproject.org"
            - Name: API_PORT
              Value: "5003"
            - Name: PORTAL_CNAME
              Value: "lightsources.materialsproject.org"
            - Name: PORTAL_PORT
              Value: "8083"
            - Name: TRADEMARK
              Value: "LS"
            - Name: NWORKERS
              Value: 1
            - Name: AWS_REGION
              Value: !Ref 'AWS::Region'
          DependsOn:
            - Condition: START
              ContainerName: api-ls
          PortMappings:
            - ContainerPort: 8083
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'ServiceName'
        - Name: orca
          MemoryReservation: 250
          Image: !Join ['', [
            !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
            !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
            !Ref 'Tag', '-orca'
          ]]
          Environment:
            - Name: START_XVFB
              Value: false
          PortMappings:
            - ContainerPort: 4444
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'ServiceName'
        - Name: gateway
          MemoryReservation: 40
          Image: !Join ['', [
            !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
            !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
            !Ref 'Tag', '-gateway'
          ]]
          Environment:
            - Name: KG_ALLOW_ORIGIN
              Value: '*'
          PortMappings:
            - ContainerPort: 8888
          LogConfiguration:
            LogDriver: 'awslogs'
            Options:
              awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'ServiceName'
        #- Name: datadog
        #  MemoryReservation: 50
        #  Image: !Join ['', [
        #    !Ref 'AWS::AccountId', '.dkr.ecr.', !Ref 'AWS::Region', '.amazonaws.com/',
        #    !Ref 'Repository', ':', !Ref 'PipelineName', '-', !Ref 'EnvironmentName', '-',
        #    !Ref 'Tag', '-datadog'
        #  ]]
        #  Environment:
        #    - Name: DD_API_KEY
        #      Value: !Ref 'DdApiKey'
        #    - Name: DD_APM_ENABLED
        #      Value: true
        #    - Name: DD_SYSTEM_PROBE_ENABLED
        #      Value: true
        #    - Name: DD_PROCESS_AGENT_ENABLED
        #      Value: true
        #    - Name: ECS_FARGATE
        #      Value: true
        #    - Name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
        #      Value: true
        #    - Name: DD_DOCKER_LABELS_AS_TAGS
        #      Value: "{\"my.custom.label.service\":\"service\"}"
        #    - Name: DD_RECEIVER_PORT
        #      Value: 8126
        #    - Name: DD_DD_URL
        #      Value: https://pvtlink.agent.datadoghq.com
        #    - Name: DD_LOGS_CONFIG_USE_HTTP
        #      Value: true
        #    - Name: DD_LOGS_CONFIG_LOGS_DD_URL
        #      Value: "pvtlink.logs.datadoghq.com:443"
        #  LogConfiguration:
        #    LogDriver: 'awslogs'
        #    Options:
        #      awslogs-group: !Join ['-', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'service', !Ref 'ServiceName']]
        #      awslogs-region: !Ref 'AWS::Region'
        #      awslogs-stream-prefix: !Ref 'ServiceName'

  # The service. The service is a resource which allows you to run multiple
  # copies of a type of task, and gather up their logs and metrics, as well
  # as monitor the number of running tasks and replace any that have crashed
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref 'ServiceName'
      Cluster:
        Fn::ImportValue:
          !Join [':', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'ClusterName']]
      LaunchType: FARGATE
      PlatformVersion: 1.4.0
      DesiredCount: 2
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - Fn::ImportValue:
                !Join [':', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'PrivateSecurityGroup']]
          Subnets:
            - Fn::ImportValue:
                !Join [':', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'PrivateSubnetOne']]
            - Fn::ImportValue:
                !Join [':', [!Ref 'PipelineName', !Ref 'EnvironmentName', 'PrivateSubnetTwo']]
      TaskDefinition: !Ref 'TaskDefinition'
