version: '2'
services:

  app:
    image: materialsproject-app
    restart: always
    tty: true
    ports:
      - 8000:8000

  #web:
  #  image: materialsproject-nginx
  #  ports:
  #    - "80:8080"
  #  volumes:
  #    - ./web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro

  tunnels:
    image: thywolf/alpine-openssh-client
    entrypoint: ssh
    stdin_open: true
    tty: true
    volumes:
      - ~/.ssh/mendel@mac14:/root/.ssh/id_rsa:ro
    command: "-N -oStrictHostKeyChecking=no -oServerAliveInterval=60 \
              -oServerAliveCountMax=2 -4 -t -i /root/.ssh/id_rsa \
              -L*:57001:mongodb01.nersc.gov:27017 \
              -L*:57002:matgen2.lbl.gov:27017 \
              -L*:57003:mongodb03.nersc.gov:27017 \
              -L*:57004:mongodb04.nersc.gov:27017 \
              huck@matgen2.lbl.gov"
