version: 1

update_configs:

  - package_manager: "python"
    directory: "mpcontribs-io"
    update_schedule: "weekly"
  - package_manager: "python"
    directory: "mpcontribs-api"
    update_schedule: "weekly"
  - package_manager: "python"
    directory: "mpcontribs-client"
    update_schedule: "weekly"
  - package_manager: "python"
    directory: "mpcontribs-portal"
    update_schedule: "weekly"

  - package_manager: "javascript"
    directory: "mpcontribs-portal"
    update_schedule: "weekly"

  - package_manager: "docker"
    directory: "mpcontribs-portal"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "mpcontribs-api"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "mpcontribs-sidecars/kernel_gateway"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "mpcontribs-sidecars/chrome"
    update_schedule: "weekly"
