version: 1

update_configs:

  # libraries (python)
  - package_manager: "python"
    directory: "mpcontribs-io"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
  - package_manager: "python"
    directory: "mpcontribs-client"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"

  # services (python)
  - package_manager: "python"
    directory: "mpcontribs-sidecars/builder"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
  - package_manager: "python"
    directory: "mpcontribs-api"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
  - package_manager: "python"
    directory: "mpcontribs-portal"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"

  # services (javascript)
  - package_manager: "javascript"
    directory: "mpcontribs-portal"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "in_range"

  # services (docker)
  - package_manager: "docker"
    directory: "mpcontribs-sidecars/kernel_gateway"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
  - package_manager: "docker"
    directory: "mpcontribs-sidecars/builder"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
  - package_manager: "docker"
    directory: "mpcontribs-sidecars/chrome"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
  - package_manager: "docker"
    directory: "mpcontribs-api"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
  - package_manager: "docker"
    directory: "mpcontribs-portal"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
  - package_manager: "docker"
    directory: "mpcontribs-sidecars/xray-daemon"
    update_schedule: "weekly"
    automerged_updates:
        - match:
            dependency_type: "all"
            update_type: "all"
