version: '2'
services:

  app:
    image: mpcontribs-app
    restart: always
    environment:
      - MPCONTRIBS_DEBUG="True"
    entrypoint: /bin/sh
    command: "-c 'cd /app/webtzite && git checkout master && git pull && bower install --allow-root && \
              cd /app/mpcontribs/users && git checkout master && git pull && cd /app && \
              sed -i 's@https://materialsproject.org/cas/@http://docker.for.mac.localhost:8000/cas/@' test_site/settings.py && \
              git pull && python manage.py collectstatic --noinput && mpcontribs --debug'"
    ports:
      - 127.0.0.2:5000:5000

  #web:
  #  image: mpcontribs-nginx
  #  ports:
  #    - "80:8080"
  #  volumes:
  #    - ./web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    image: selenium/standalone-chrome-debug:3.14.0-iron

  #mongo:
  #  image: mongo
  #  restart: always
  #  command: --noauth
  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example

  #jupyter:
  #  image: jupyter/base-notebook
  #  command: /usr/local/bin/start-singleuser.sh
