name: base
channels:
  - conda-forge
  - defaults
dependencies:
    - apispec
    - dnspython
    - Flask
    - flask-cors
    - flask-marshmallow
    - marshmallow
    - mongoengine
    - pymongo
    - requests
    - selenium
    - beautifulsoup4
    - nbformat
    - jupyter_client
    - ipykernel
    - more-itertools
    - jupyter_enterprise_gateway
    - pandas
    - pymatgen
    - gunicorn
    - gevent
    - werkzeug
    - plotly
    - PyYAML
    - pip
    - pip:
        - flask-mongoengine
        - toronado
        - css-html-js-minify
        - flask-log
        - dict-deep
