name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - nomkl
  - conda
  - pip
  - ipywidgets
  - notebook==5.7.8
  - pandas
  - pymatgen
  - plotly
  - bravado
  - service_identity
  - ipython
  - matplotlib
  - jupyterhub==1.0.0
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pip:
      - jhub_remote_user_authenticator
      - nbgitpuller
      - nbzip
      - fargatespawner
      - jupyterhub-simplespawner
      - fido>=4.2.2
      - archieml>=0.3.4

  #- tini=0.18.0
  #- jupyterlab=0.35.5
  #- numexpr=2.6
  #- dill=0.2
  #- numba=0.42
  #- xlrd
  #- protobuf=3.7
  #- hdf5=1.10
  #- statsmodels=0.9
  #- beautifulsoup4=4.7
  #- scikit-image=0.14
  #- scikit-learn=0.20
  #- sympy=1.3
  #- patsy=0.5
  #- bokeh
  #- dask
  #- vincent=0.4
  #- cython=0.29
  #- cloudpickle=0.8
  #- conda-forge::blas[build=openblas]
  #- seaborn=0.9
  #- sqlalchemy=1.3
  #- scipy
  #- h5py=2.9
  #- numpy
  #- jupyter_enterprise_gateway
  #- jsonschema
  #- crochet
  #- typing-extensions
  #- msgpack-python
  #- twisted
  #- pyyaml
  #- pytest
  #- strict-rfc3339
  #- pip:
  #    - yelp-encodings>=0.1.3
  #    - yelp-bytes>=0.3.0
  #    - plotly_express
