name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - nomkl
  - conda
  - pip
  - ipywidgets
  - notebook==5.7.8
  - pandas
  - pymatgen
  - plotly
  - bravado
  - service_identity
  - ipython
  - matplotlib
  - jupyterhub==1.0.0
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pandas-datareader
  - plotly_express
  - jupyter_enterprise_gateway
  - pip:
      - jhub_remote_user_authenticator
      - nbgitpuller
      - nbzip
      - fargatespawner
      - jupyterhub-simplespawner
      - fido>=4.2.2
      - archieml>=0.3.4
