name: MPContribs testing
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: build the stack
      run: docker-compose up -d api
    - name: test
      run: docker run --network container:api appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
